modLoader="javafml"
license="All rights reserved"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/High-Fox/minimal-tweaks/issues"
[[mods]]
    modId="minimaltweaks"
    version="${version}"
    displayName="Minimal Tweaks"
    authors="HighFox"
    description='''
Barely noticable tweaks that just make sense.
    '''